# Generated by Django 6.0.4 on 2026-04-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_image_project_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
